### ISSUE TITLE
Support for rxjs 7.x.x

### ISSUE THREAD

**Issue by wenche** [robinpyon/sanity-plugin-media#79]
rxjs is listed as a peer dependency in package.json
`"rxjs": "^6.5.3",`

It would be nice to support newer versions for rxjs. With
`"rxjs": "^7.5.4",` in our code base, the media tab will crash with the following error
```
Scheduler.js:10 
        
Uncaught TypeError: this.schedulerActionCtor is not a constructor
    at QueueScheduler.Scheduler.schedule (Scheduler.js:10:1)
    at executeSchedule (executeSchedule.js:4:1)
    at observeOn.js:7:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:15:1)
    at OperatorSubscriber.Subscriber.next (Subscriber.js:34:1)
    at Subject.js:41:1
    at errorContext (errorContext.js:19:1)
    at Subject.next (Subject.js:31:1)
    at AnonymousSubject.next (Subject.js:145:1)
    at createEpicMiddleware.js:58:1
```

**Comment by robinpyon** [comment]
Thanks for flagging this @wenche.

rxjs is no longer a peer dependency in `1.4.9`, and the plugin will now work if you have rxjs 7.x installed in your studio. Do shout if you have any issues here.
